name: Documentation

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      TEST_DOCS_REPOSITORY: rmisev/test-docs
      TEST_DOCS_DIR: main
    steps:
      - uses: actions/checkout@v4

      # Deploy
      - name: Checkout ${{ env.TEST_DOCS_REPOSITORY }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TEST_DOCS_REPOSITORY }}
          ref: gh-pages
          path: build-docs

      - name: Prepare directory
        run: |
          mkdir -p build-docs
          rm -rf build-docs/.git
          rm -rf build-docs/common
          rm -rf build-docs/${{ env.TEST_DOCS_DIR }}
          cp -r doc/html build-docs/common
          mv doc/html build-docs/${{ env.TEST_DOCS_DIR }}
          cp doc/index.html build-docs

      - name: Deploy to ${{ env.TEST_DOCS_REPOSITORY }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          repository-name: ${{ env.TEST_DOCS_REPOSITORY }}
          folder: build-docs
