name: Upload release assets

on:
  release:
    types: [published]

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload assets
        run: gh release upload ${{ github.ref_name }} src/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
