name: Windows

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: windows-2025
    strategy:
      matrix:
        include:
          - name: g++ C++17
            generator: Ninja
            cxx_standard: 17
            cmake_options: "-DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release"
            cmd: build/bandymas

          - name: VS 2022 v142 C++17
            generator: "Visual Studio 17 2022"
            cxx_standard: 17
            cmake_options: "-A x64 -T v142"
            cmd: build/Release/bandymas

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -S . -B build -G "${{ matrix.generator }}" -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} ${{ matrix.cmake_options }}
    - name: build
      run: cmake --build build --config Release
    - name: run
      run: ${{ matrix.cmd }}
